<a href="https://colab.research.google.com/github/ykitaguchi77/GO_proteomics/blob/main/GO_labodata_analysis.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#**GO_labo_data_analysis**

In [1]:
from google.colab import drive
drive.mount("/content/drive")

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
!pip install japanize_matplotlib --q
import japanize_matplotlib


pd.set_option('display.max_rows', 200)
pd.set_option('display.max_columns', 200)

Mounted at /content/drive

In [2]:
# Reload the CSV files into DataFrames using the Shift-JIS encoding
df_disease_info = pd.read_csv('/content/drive/MyDrive/研究/進行中の研究/甲状腺眼症プロテオミクス/甲状腺眼症採血/●DiseaseInfo_modified1.5_connected_9800.csv', encoding='shift-jis')
df_patient_labo = pd.read_csv('/content/drive/MyDrive/研究/進行中の研究/甲状腺眼症プロテオミクス/甲状腺眼症採血/patient_labodata_list.csv', encoding='cp932')

# Convert the 'PATIENTNO' in df_patient_labo and 'Unnamed: 0' in df_disease_info to integer type
df_patient_labo['PATIENTNO'] = df_patient_labo['PATIENTNO'].astype(int)
df_disease_info['Unnamed: 0'] = df_disease_info['Unnamed: 0'].astype('Int64', errors='ignore')

# Find matching rows based on 'PATIENTNO' and 'Unnamed: 0'
matching_rows = pd.merge(df_patient_labo, df_disease_info, left_on='PATIENTNO', right_on='Unnamed: 0', how='inner')



# Create new columns in df_patient_labo and initialize them with None
new_col_names_8th = 'severity'
new_col_names_9th = 'activity'
df_patient_labo[new_col_names_8th] = None
df_patient_labo[new_col_names_9th] = None

# Create a mapping dictionary from 'PATIENTNO' to 8th and 9th columns in matching_rows
col_name_8th = matching_rows.columns[44]
col_name_9th = matching_rows.columns[45]
map_dict_8th = dict(zip(matching_rows['PATIENTNO'], matching_rows[col_name_8th]))
map_dict_9th = dict(zip(matching_rows['PATIENTNO'], matching_rows[col_name_9th]))

# Use the mapping dictionary to populate the new columns in df_patient_labo
df_patient_labo[new_col_names_8th] = df_patient_labo['PATIENTNO'].map(map_dict_8th)
df_patient_labo[new_col_names_9th] = df_patient_labo['PATIENTNO'].map(map_dict_9th)

# 患者IDの匿名化
# 一意なPATIENTNOを取得
unique_patient_no = df_patient_labo['PATIENTNO'].unique()
# 一意なPATIENTNOに通し番号を割り当てる
mapping = {patient_no: i for i, patient_no in enumerate(unique_patient_no)}
# PATIENTNO列を通し番号に置き換え
df_patient_labo['PATIENTNO'] = df_patient_labo['PATIENTNO'].map(mapping)


# 患者氏名の列を削除
df_patient_labo = df_patient_labo.drop("漢字氏名", axis=1)

df_patient_labo

<ipython-input-2-07a3a09428f1>:2: DtypeWarning: Columns (6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,21,22,43,45,46,48,49,50,51,52,53,54,55,56,57,58,59,60,61,62,63,64,65,66,67,68,69,70,71,72,73,74,75,76,77,78,79,80,81,82,83,84,85,88,89,101,103,104,105,106,107,108,109,110,117,119,120,124,131,133,134,135,136,137) have mixed types. Specify dtype option on import or set low_memory=False.
  df_disease_info = pd.read_csv('/content/drive/MyDrive/研究/進行中の研究/甲状腺眼症プロテオミクス/甲状腺眼症採血/●DiseaseInfo_modified1.5_connected_9800.csv', encoding='shift-jis')

,PATIENTNO,性別,生年月日,検査時年齢,ORDERNO,検査日,検査時間,WBC(白血球数),RBC(赤血球数),Hb(ﾍﾓｸﾞﾛﾋﾞﾝ),Ht(ﾍﾏﾄｸﾘｯﾄ),ＭＣＶ,ＭＣＨ,ＭＣＨＣ,好中球(機械法),ﾘﾝﾊﾟ球(機械法),好酸球(機械法),AST(GOT),ALT(GPT),T-Cho(総ｺﾚｽﾃﾛｰﾙ),TG(中性脂肪),ＣＲＰ,TP(総ﾀﾝﾊﾟｸ),ＦＴ３,ＴＲＡｂ,ＴＳＡｂ,TPOAb,ＴＳＨ,ＩｇＧ,オーダー診療科,入院診療科,外来診療科_1,外来診療科_2,外来診療科_3,外来診療科_4,severity,activity
0,0,F,1936/4/5,77,291802727.0,2014/2/28,0,3.73,4.00,11.6,35.9,89.8,29.0,32.3,62.0,33.2,0.5,19.0,13.0,186.0,90.0,0.04ﾐﾏﾝ,7.0,NaN,NaN,NaN,NaN,NaN,NaN,眼科,NaN,眼科,NaN,NaN,NaN,甲状腺眼症（軽症）,不活動期
1,1,M,1937/1/21,83,436841269.0,2020/7/14,0,4.77,5.39,17.4,50.3,93.3,32.3,34.6,65.6,23.5,2.1,25.0,19.0,224.0,290.0,0.06,7.1,NaN,NaN,NaN,NaN,NaN,NaN,眼科,NaN,眼科,NaN,NaN,NaN,NaN,NaN
2,1,M,1937/1/21,86,516012541.0,2023/8/29,0,6.22,4.20,13.4,40.9,97.4,31.9,32.8,69.2,19.5,2.3,43.0,48.0,202.0,141.0,0.04ﾐﾏﾝ,7.6,NaN,NaN,NaN,NaN,NaN,NaN,眼科,NaN,眼科,NaN,NaN,NaN,NaN,NaN
3,2,F,1940/6/20,73,290153833.0,2014/1/6,0,13.23,4.43,13.0,39.7,89.6,29.3,32.7,84.8,11.3,1.0,16.0,14.0,NaN,NaN,1.35,6.7,NaN,NaN,NaN,NaN,NaN,NaN,呼吸器内科,NaN,旧）第一内科,NaN,NaN,NaN,NaN,NaN
4,2,F,1940/6/20,73,290827014.0,2014/2/10,0,11.61,4.89,14.3,45.0,92.0,29.2,31.8,81.8,14.7,0.7,19.0,18.0,NaN,NaN,0.06,7.3,NaN,NaN,NaN,NaN,NaN,NaN,呼吸器内科,NaN,旧）第一内科,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3896,266,F,1970/6/5,53,516229984.0,2023/9/6,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,746.0,NaN,NaN,NaN,眼科,NaN,眼科,放射線科,NaN,NaN,NaN,NaN
3897,267,M,1961/7/22,62,515865202.0,2023/8/23,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2.5,NaN,1650.0,<3.0,3.82,NaN,眼科,NaN,眼科,NaN,NaN,NaN,NaN,NaN
3898,268,F,1963/5/25,60,516049004.0,2023/8/30,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2.5,NaN,130.0,<3.0,0.26,NaN,眼科,NaN,眼科,NaN,NaN,NaN,NaN,NaN
3899,269,F,1951/10/22,71,515104779.0,2023/7/26,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2.1,NaN,310.0,77.6,6.00,NaN,眼科,NaN,眼科,NaN,NaN,NaN,NaN,NaN
3900,270,M,1997/5/18,26,515898548.0,2023/8/24,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2.9,<0.9,101.0,<3.0,1.22,NaN,眼科,NaN,眼科,NaN,NaN,NaN,NaN,NaN

In [ ]:
#############################
# 各患者に関して初回の採血のみを抜粋
#############################

# '検査日'列を日付型に変換
df_patient_labo['検査日'] = pd.to_datetime(df_patient_labo['検査日'], errors='coerce')

# 同じPATIENTNOに対して、検査日が古いもののみ残す
df_patient_labo_filtered = df_patient_labo.sort_values(by=['PATIENTNO', '検査日']).drop_duplicates(subset='PATIENTNO', keep='first')

df_patient_labo_filtered

In [20]:
df = df_patient_labo_filtered

# Assuming df is your DataFrame
df_active = pd.concat([
    df[df["activity"] == "活動期（ステロイドあり）"],
    df[df["activity"] == "活動期（ステロイドなし）"]
])
df_inactive = df[df["activity"]=="不活動期"]
df_others = df[~df['activity'].isin(['活動期（ステロイドあり）', '活動期（ステロイドなし）'])]

print(f"Active GO: {len(df_active)}, inactive GO: {len(df_inactive)}, others: {len(df_others)}")

Active GO: 90, inactive GO: 18, others: 181

In [18]:
df_active.to_csv("/content/drive/MyDrive/研究/進行中の研究/甲状腺眼症プロテオミクス/甲状腺眼症採血/activeGO.csv", encoding='cp932', index=False)
df_inactive.to_csv("/content/drive/MyDrive/研究/進行中の研究/甲状腺眼症プロテオミクス/甲状腺眼症採血/othersGO.csv", encoding='cp932', index=False)
df_others.to_csv("/content/drive/MyDrive/研究/進行中の研究/甲状腺眼症プロテオミクス/甲状腺眼症採血/othersGO.csv", encoding='cp932', index=False)

In [ ]:
"""
データのクリーンニング
"""
# Columns to be compared
columns_to_compare = [
    "WBC(白血球数)", "RBC(赤血球数)", "Hb(ﾍﾓｸﾞﾛﾋﾞﾝ)", "Ht(ﾍﾏﾄｸﾘｯﾄ)", "ＭＣＶ", "ＭＣＨ", "ＭＣＨＣ",
    "好中球(機械法)", "ﾘﾝﾊﾟ球(機械法)", "好酸球(機械法)", "AST(GOT)", "ALT(GPT)", "T-Cho(総ｺﾚｽﾃﾛｰﾙ)",
    "TG(中性脂肪)", "ＣＲＰ", "TP(総ﾀﾝﾊﾟｸ)", "ＦＴ３", "ＴＲＡｂ", "ＴＳＡｂ", "TPOAb", "ＴＳＨ", "ＩｇＧ"
]

# Function to clean and convert the data with additional handling for '>', '<', and 'ﾐﾏﾝ'
def clean_and_convert_final(df, columns):
    for col in columns:
        # Replace '<', '>', and 'ﾐﾏﾝ' with empty string and convert to float
        df[col] = df[col].apply(lambda x: np.nan if pd.isna(x) else float(str(x).replace('<', '').replace('>', '').replace('ﾐﾏﾝ', '')))
    return df

# Clean and convert the data in both DataFrames
df_active_clean = clean_and_convert_final(df_active.copy(), columns_to_compare)
df_inactive_clean = clean_and_convert_final(df_inactive.copy(), columns_to_compare)
df_others_clean = clean_and_convert_final(df_others.copy(), columns_to_compare)

# Show the first few rows of the cleaned DataFrames for verification
df_active_clean.head()

In [ ]:
"""
Compare labodata between active and others
"""

# Initialize the comparison results as an empty dictionary
comparison_results = {}

# Loop through each column to compare
for col in columns_to_compare:
    # Skip the column if it doesn't exist in either DataFrame
    if col not in df_active_clean.columns or col not in df_others_clean.columns:
        continue

    # Extract the data for the column from both DataFrames
    active_data = df_active_clean[col].dropna()
    inactive_data = df_inactive_clean[col].dropna()
    others_data = df_others_clean[col].dropna()

    # Create a subplot for the comparison
    plt.figure(figsize=(12, 6))
    sns.histplot(active_data, kde=True, color='b', label='Active', bins=50, alpha=0.5)
    sns.histplot(inactive_data, kde=True, color='b', label='Active', bins=50, alpha=0.5)
    sns.histplot(others_data, kde=True, color='r', label='Others', bins=50, alpha=0.5)
    plt.title(f'Comparison of {col}')
    plt.xlabel(col)
    plt.ylabel('Frequency')
    plt.legend()
    plt.show()

    # Compute summary statistics for the column for both DataFrames
    summary_active = active_data.describe()
    summary_inactive = inactive_data.describe()
    summary_others = others_data.describe()

    # Store the summary statistics in the comparison results dictionary
    comparison_results[col] = {'active': summary_active, 'inactive': summary_inactive,'others': summary_others}

# Show some of the comparison results as an example
#example_keys = list(comparison_results.keys())[:3]
example_keys = list(comparison_results.keys())
for key in example_keys:
    print(f"{key}: {comparison_results[key]}\n")

In [27]:
from scipy.stats import ttest_ind

# Initialize a dictionary to store the p-values for each column
p_values = {}

# Loop through each column to perform t-tests
for col in columns_to_compare:
    # Skip the column if it doesn't exist in either DataFrame
    if col not in df_active_clean.columns or col not in df_others_clean.columns:
        continue

    # Extract the data for the column from both DataFrames
    active_data = df_active_clean[col].dropna()
    others_data = df_inactive_clean[col].dropna()

    # Perform an independent t-test
    t_stat, p_val = ttest_ind(active_data, others_data, equal_var=False, nan_policy='omit')

    # Store the p-value in the dictionary
    p_values[col] = p_val

# Show the p-values
p_values

/usr/local/lib/python3.10/dist-packages/scipy/stats/_stats_py.py:1103: RuntimeWarning: divide by zero encountered in divide
  var *= np.divide(n, n-ddof)  # to avoid error on division by zero
/usr/local/lib/python3.10/dist-packages/scipy/stats/_stats_py.py:1103: RuntimeWarning: invalid value encountered in double_scalars
  var *= np.divide(n, n-ddof)  # to avoid error on division by zero

{'WBC(白血球数)': 0.7330483105934549,
 'RBC(赤血球数)': 0.8864283148535846,
 'Hb(ﾍﾓｸﾞﾛﾋﾞﾝ)': 0.688322024356968,
 'Ht(ﾍﾏﾄｸﾘｯﾄ)': 0.8355392428603585,
 'ＭＣＶ': 0.5762993850054332,
 'ＭＣＨ': 0.4075146214438735,
 'ＭＣＨＣ': 0.32435323761469204,
 '好中球(機械法)': 0.8697382948131589,
 'ﾘﾝﾊﾟ球(機械法)': 0.7423973412509852,
 '好酸球(機械法)': 0.5625137109712717,
 'AST(GOT)': 0.6637598849411919,
 'ALT(GPT)': 0.6008689458229284,
 'T-Cho(総ｺﾚｽﾃﾛｰﾙ)': 0.03708305101904266,
 'TG(中性脂肪)': 0.8283787705480212,
 'ＣＲＰ': 0.24828199478279936,
 'TP(総ﾀﾝﾊﾟｸ)': 0.5982617980229692,
 'ＦＴ３': 0.6786222848984009,
 'ＴＲＡｂ': 0.09530535807859476,
 'ＴＳＡｂ': 0.03531698341803362,
 'TPOAb': 0.2618256294921362,
 'ＴＳＨ': 0.06266467107384942,
 'ＩｇＧ': nan}